name:                dominoes-puzzle
version:             0.1.0.0
github:              "mpilgrem/dominoes-puzzle"
license:             BSD3
author:              "Mike Pilgrem"
maintainer:          "public@pilgrem.com"
copyright:           "Copyright 2018 Mike Pilgrem"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Test

description:         Please see the README on GitHub at
                     <https://github.com/mpilgrem/dominoes-puzzle#readme>

dependencies:
- base >= 4.7 && < 5
- array
- code-page
- mtl

library:
  source-dirs: src

executables:
  dominoes:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dominoes-puzzle
